# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ahubchak/ide/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/ahubchak/ide/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ahubchak/CLionProjects/AES Tool"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ahubchak/CLionProjects/AES Tool"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ahubchak/ide/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ahubchak/ide/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ahubchak/CLionProjects/AES Tool/CMakeFiles" "/home/ahubchak/CLionProjects/AES Tool/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ahubchak/CLionProjects/AES Tool/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AES_Tool

# Build rule for target.
AES_Tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AES_Tool
.PHONY : AES_Tool

# fast build rule for target.
AES_Tool/fast:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/build
.PHONY : AES_Tool/fast

LibTomCrypt/src/ciphers/aes/aes.o: LibTomCrypt/src/ciphers/aes/aes.c.o

.PHONY : LibTomCrypt/src/ciphers/aes/aes.o

# target to build an object file
LibTomCrypt/src/ciphers/aes/aes.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/ciphers/aes/aes.c.o
.PHONY : LibTomCrypt/src/ciphers/aes/aes.c.o

LibTomCrypt/src/ciphers/aes/aes.i: LibTomCrypt/src/ciphers/aes/aes.c.i

.PHONY : LibTomCrypt/src/ciphers/aes/aes.i

# target to preprocess a source file
LibTomCrypt/src/ciphers/aes/aes.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/ciphers/aes/aes.c.i
.PHONY : LibTomCrypt/src/ciphers/aes/aes.c.i

LibTomCrypt/src/ciphers/aes/aes.s: LibTomCrypt/src/ciphers/aes/aes.c.s

.PHONY : LibTomCrypt/src/ciphers/aes/aes.s

# target to generate assembly for a file
LibTomCrypt/src/ciphers/aes/aes.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/ciphers/aes/aes.c.s
.PHONY : LibTomCrypt/src/ciphers/aes/aes.c.s

LibTomCrypt/src/ciphers/aes/aes_tab.o: LibTomCrypt/src/ciphers/aes/aes_tab.c.o

.PHONY : LibTomCrypt/src/ciphers/aes/aes_tab.o

# target to build an object file
LibTomCrypt/src/ciphers/aes/aes_tab.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/ciphers/aes/aes_tab.c.o
.PHONY : LibTomCrypt/src/ciphers/aes/aes_tab.c.o

LibTomCrypt/src/ciphers/aes/aes_tab.i: LibTomCrypt/src/ciphers/aes/aes_tab.c.i

.PHONY : LibTomCrypt/src/ciphers/aes/aes_tab.i

# target to preprocess a source file
LibTomCrypt/src/ciphers/aes/aes_tab.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/ciphers/aes/aes_tab.c.i
.PHONY : LibTomCrypt/src/ciphers/aes/aes_tab.c.i

LibTomCrypt/src/ciphers/aes/aes_tab.s: LibTomCrypt/src/ciphers/aes/aes_tab.c.s

.PHONY : LibTomCrypt/src/ciphers/aes/aes_tab.s

# target to generate assembly for a file
LibTomCrypt/src/ciphers/aes/aes_tab.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/ciphers/aes/aes_tab.c.s
.PHONY : LibTomCrypt/src/ciphers/aes/aes_tab.c.s

LibTomCrypt/src/encauth/ccm/ccm_memory.o: LibTomCrypt/src/encauth/ccm/ccm_memory.c.o

.PHONY : LibTomCrypt/src/encauth/ccm/ccm_memory.o

# target to build an object file
LibTomCrypt/src/encauth/ccm/ccm_memory.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/encauth/ccm/ccm_memory.c.o
.PHONY : LibTomCrypt/src/encauth/ccm/ccm_memory.c.o

LibTomCrypt/src/encauth/ccm/ccm_memory.i: LibTomCrypt/src/encauth/ccm/ccm_memory.c.i

.PHONY : LibTomCrypt/src/encauth/ccm/ccm_memory.i

# target to preprocess a source file
LibTomCrypt/src/encauth/ccm/ccm_memory.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/encauth/ccm/ccm_memory.c.i
.PHONY : LibTomCrypt/src/encauth/ccm/ccm_memory.c.i

LibTomCrypt/src/encauth/ccm/ccm_memory.s: LibTomCrypt/src/encauth/ccm/ccm_memory.c.s

.PHONY : LibTomCrypt/src/encauth/ccm/ccm_memory.s

# target to generate assembly for a file
LibTomCrypt/src/encauth/ccm/ccm_memory.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/encauth/ccm/ccm_memory.c.s
.PHONY : LibTomCrypt/src/encauth/ccm/ccm_memory.c.s

LibTomCrypt/src/misc/crypt/crypt_argchk.o: LibTomCrypt/src/misc/crypt/crypt_argchk.c.o

.PHONY : LibTomCrypt/src/misc/crypt/crypt_argchk.o

# target to build an object file
LibTomCrypt/src/misc/crypt/crypt_argchk.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_argchk.c.o
.PHONY : LibTomCrypt/src/misc/crypt/crypt_argchk.c.o

LibTomCrypt/src/misc/crypt/crypt_argchk.i: LibTomCrypt/src/misc/crypt/crypt_argchk.c.i

.PHONY : LibTomCrypt/src/misc/crypt/crypt_argchk.i

# target to preprocess a source file
LibTomCrypt/src/misc/crypt/crypt_argchk.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_argchk.c.i
.PHONY : LibTomCrypt/src/misc/crypt/crypt_argchk.c.i

LibTomCrypt/src/misc/crypt/crypt_argchk.s: LibTomCrypt/src/misc/crypt/crypt_argchk.c.s

.PHONY : LibTomCrypt/src/misc/crypt/crypt_argchk.s

# target to generate assembly for a file
LibTomCrypt/src/misc/crypt/crypt_argchk.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_argchk.c.s
.PHONY : LibTomCrypt/src/misc/crypt/crypt_argchk.c.s

LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.o: LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.o

.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.o

# target to build an object file
LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.o
.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.o

LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.i: LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.i

.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.i

# target to preprocess a source file
LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.i
.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.i

LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.s: LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.s

.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.s

# target to generate assembly for a file
LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.s
.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.c.s

LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.o: LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.o

.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.o

# target to build an object file
LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.o
.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.o

LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.i: LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.i

.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.i

# target to preprocess a source file
LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.i
.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.i

LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.s: LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.s

.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.s

# target to generate assembly for a file
LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.s
.PHONY : LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.c.s

LibTomCrypt/src/misc/crypt/crypt_find_cipher.o: LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.o

.PHONY : LibTomCrypt/src/misc/crypt/crypt_find_cipher.o

# target to build an object file
LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.o
.PHONY : LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.o

LibTomCrypt/src/misc/crypt/crypt_find_cipher.i: LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.i

.PHONY : LibTomCrypt/src/misc/crypt/crypt_find_cipher.i

# target to preprocess a source file
LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.i
.PHONY : LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.i

LibTomCrypt/src/misc/crypt/crypt_find_cipher.s: LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.s

.PHONY : LibTomCrypt/src/misc/crypt/crypt_find_cipher.s

# target to generate assembly for a file
LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.s
.PHONY : LibTomCrypt/src/misc/crypt/crypt_find_cipher.c.s

LibTomCrypt/src/misc/crypt/crypt_register_cipher.o: LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.o

.PHONY : LibTomCrypt/src/misc/crypt/crypt_register_cipher.o

# target to build an object file
LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.o
.PHONY : LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.o

LibTomCrypt/src/misc/crypt/crypt_register_cipher.i: LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.i

.PHONY : LibTomCrypt/src/misc/crypt/crypt_register_cipher.i

# target to preprocess a source file
LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.i
.PHONY : LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.i

LibTomCrypt/src/misc/crypt/crypt_register_cipher.s: LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.s

.PHONY : LibTomCrypt/src/misc/crypt/crypt_register_cipher.s

# target to generate assembly for a file
LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.s
.PHONY : LibTomCrypt/src/misc/crypt/crypt_register_cipher.c.s

LibTomCrypt/src/misc/mem_neq.o: LibTomCrypt/src/misc/mem_neq.c.o

.PHONY : LibTomCrypt/src/misc/mem_neq.o

# target to build an object file
LibTomCrypt/src/misc/mem_neq.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/mem_neq.c.o
.PHONY : LibTomCrypt/src/misc/mem_neq.c.o

LibTomCrypt/src/misc/mem_neq.i: LibTomCrypt/src/misc/mem_neq.c.i

.PHONY : LibTomCrypt/src/misc/mem_neq.i

# target to preprocess a source file
LibTomCrypt/src/misc/mem_neq.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/mem_neq.c.i
.PHONY : LibTomCrypt/src/misc/mem_neq.c.i

LibTomCrypt/src/misc/mem_neq.s: LibTomCrypt/src/misc/mem_neq.c.s

.PHONY : LibTomCrypt/src/misc/mem_neq.s

# target to generate assembly for a file
LibTomCrypt/src/misc/mem_neq.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/mem_neq.c.s
.PHONY : LibTomCrypt/src/misc/mem_neq.c.s

LibTomCrypt/src/misc/zeromem.o: LibTomCrypt/src/misc/zeromem.c.o

.PHONY : LibTomCrypt/src/misc/zeromem.o

# target to build an object file
LibTomCrypt/src/misc/zeromem.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/zeromem.c.o
.PHONY : LibTomCrypt/src/misc/zeromem.c.o

LibTomCrypt/src/misc/zeromem.i: LibTomCrypt/src/misc/zeromem.c.i

.PHONY : LibTomCrypt/src/misc/zeromem.i

# target to preprocess a source file
LibTomCrypt/src/misc/zeromem.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/zeromem.c.i
.PHONY : LibTomCrypt/src/misc/zeromem.c.i

LibTomCrypt/src/misc/zeromem.s: LibTomCrypt/src/misc/zeromem.c.s

.PHONY : LibTomCrypt/src/misc/zeromem.s

# target to generate assembly for a file
LibTomCrypt/src/misc/zeromem.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/LibTomCrypt/src/misc/zeromem.c.s
.PHONY : LibTomCrypt/src/misc/zeromem.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/AES_Tool.dir/build.make CMakeFiles/AES_Tool.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AES_Tool"
	@echo "... LibTomCrypt/src/ciphers/aes/aes.o"
	@echo "... LibTomCrypt/src/ciphers/aes/aes.i"
	@echo "... LibTomCrypt/src/ciphers/aes/aes.s"
	@echo "... LibTomCrypt/src/ciphers/aes/aes_tab.o"
	@echo "... LibTomCrypt/src/ciphers/aes/aes_tab.i"
	@echo "... LibTomCrypt/src/ciphers/aes/aes_tab.s"
	@echo "... LibTomCrypt/src/encauth/ccm/ccm_memory.o"
	@echo "... LibTomCrypt/src/encauth/ccm/ccm_memory.i"
	@echo "... LibTomCrypt/src/encauth/ccm/ccm_memory.s"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_argchk.o"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_argchk.i"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_argchk.s"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.o"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.i"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_cipher_descriptor.s"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.o"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.i"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_cipher_is_valid.s"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_find_cipher.o"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_find_cipher.i"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_find_cipher.s"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_register_cipher.o"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_register_cipher.i"
	@echo "... LibTomCrypt/src/misc/crypt/crypt_register_cipher.s"
	@echo "... LibTomCrypt/src/misc/mem_neq.o"
	@echo "... LibTomCrypt/src/misc/mem_neq.i"
	@echo "... LibTomCrypt/src/misc/mem_neq.s"
	@echo "... LibTomCrypt/src/misc/zeromem.o"
	@echo "... LibTomCrypt/src/misc/zeromem.i"
	@echo "... LibTomCrypt/src/misc/zeromem.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

